<template>
  <div class="square-grid">
    <span
      v-for="(square, index) in map"
      :key="index"
      class="square"
      :style="{
        left: square.x * 256 + 'px',
        top: square.y * 256 + 'px',
        zoom: zoom
      }"
    >
      <span class="clickable-square"
        :class="{
          'hovered': square.x === highlightedsquare[0] && square.y === highlightedsquare[1]
        }"
        @click="clickSquare(square.x, square.y)"
        @mouseover="hoverSquare(square.x, square.y)">
        <div class="tool-tip">
          <i class="tool-tip__icon">i</i>
          <p class="tool-tip__info">
              <span class="info">
                <span class="info__title">Owner:</span> Byteme8199
              </span>
              <span class="info">
                <span class="info__title">Defense:</span> 13
              </span>
          </p>
        </div>
      </span>   
      <span
        class="inner-square"
        :style="{backgroundImage:'url(/img/squares/' + square.square + '.png)', 'z-index': index}"
        :class="tileLighting(square.x, square.y)"
      >
      </span>
      <span
        class="addon"
        v-if="square.addon"
        :style="{backgroundImage:'url(/img/addons/' + square.addon.graphic + ')', 'z-index': index + 1}"
        :class="tileLighting(square.x, square.y)"
      >
      </span>
    </span>
  </div>
</template>
<style>
  body { background-color: #222 ;}
  .square-grid {
    white-space:nowrap;
    position: relative;
  }
  /* .square-row {
    display: block;
    position: relative;
    height: 256px;
  } */
  .square {
    height: 256px;
    width: 256px;
    position: absolute;
  }
  .inner-square {
    position: absolute;
    bottom: 0px;
    width: 256px;
    height: 384px;
    filter: brightness(25%);
  }
  .addon {
    position: absolute;
    bottom: 0px;
    filter: brightness(25%);
    width: 256px;
    height: 384px;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
  }
  .bright {
    filter: brightness(100%);
  }
  .dim {
    filter: brightness(50%);
  }
  .clickable-square {
    position: absolute;
    bottom: 0px;
    cursor: pointer;
    height: 256px;
    width: 256px;
    display: block;
    z-index: 99999999;
  }
  .hovered {
    background-color: rgba(255,255,255,0.2);
  }
  /* .unknown {
    filter: brightness(65%) grayscale(70%);
    background-image: url('/img/squares/base.png') !important;
  } */
  .fogged {
    filter: brightness(45%) grayscale(70%);
  }
  /************** Tool Tip Styles ********************************/
  .tool-tip {
    display: inline-block;
    position: relative;
    margin-left: 0.5em;
  }
  .tool-tip .tool-tip__icon {
    cursor: pointer;
    display: inline-block;
    font-style: italic;
    font-family: times new roman;
    height: 256px;
    line-height: 1.3em;
    text-align: center;
    width: 256px;
  }
  .tool-tip .tool-tip__info {
    display: none;
    background: #262626;
    border: 1px solid #666;
    border-radius: 3px;
    font-size: 0.875em;
    padding: 1em;
    position: absolute;
    left: 75px;
    top: -22px;
    width: 250px;
    z-index: 2;
    zoom: 4;
    filter: drop-shadow(5px 10px 8px rgba(0,0,0,0.8));
  }
  .tool-tip .tool-tip__info:before, .tool-tip .tool-tip__info:after {
    content: "";
    position: absolute;
    left: -10px;
    top: 7px;
    border-style: solid;
    border-width: 10px 10px 10px 0;
    border-color: transparent #666;
  }
  .tool-tip .tool-tip__info:after {
    left: -8px;
    border-right-color: #262626;
  }
  .tool-tip .tool-tip__info .info {
    display: block;
  }
  .tool-tip .tool-tip__info .info__title {
    color: white;
  }
  .info {
    color: #BBB;
  }
  .tool-tip:hover .tool-tip__info, .tool-tip:focus .tool-tip__info {
    display: inline-block;
  }
  a:focus + .tool-tip .tool-tip__info {
    display: inline-block;
  }
</style>
<script>
export default {
  name: "Game",
  methods: {
    clickSquare(x, y) {
      console.log(x, y)
    },
    hoverSquare(x, y) {
      this.highlightedsquare = [x, y];
    },
    tileLighting(x, y) {
      let isBright = false
      let isDim = false
      let isDark = false

      this.map.forEach((tile) => {
        if(tile.bright) {
          let lowX = tile.x - tile.bright;
          let highX = tile.x + tile.bright;
          let lowY = tile.y - tile.bright;
          let highY = tile.y + tile.bright;
          if((x > lowX && x < highX) && (y > lowY && y < highY)) {
            isBright = true;
          }
        }
        if(tile.dim && !isBright) {
          let lowX = tile.x - tile.dim;
          let highX = tile.x + tile.dim;
          let lowY = tile.y - tile.dim;
          let highY = tile.y + tile.dim;
          if((x > lowX && x < highX) && (y > lowY && y < highY)) {
            isDim = true;
          }
        }
      })
      return {
        'bright': isBright,
        'dim': isDim,
        'dark': isDark
      }
    }
  },
  data() {
    return {
      highlightedsquare: [],
      zoom: 0.25,
      map: [
          { x: 0, y: 0, square: 'forestPine02' },
          { x: 1, y: 0, square: 'forestPine02' },
          { x: 2, y: 0, square: 'forestPine02' },
          { x: 3, y: 0, square: 'forestPine02' },
          { x: 4, y: 0, square: 'forestPine02' },
          { x: 5, y: 0, square: 'forestPine02' },
          { x: 6, y: 0, square: 'forestPine02' },
          { x: 7, y: 0, square: 'forestPine02' },
          { x: 8, y: 0, square: 'forestPine02' },
          { x: 9, y: 0, square: 'forestPine02' },
          { x: 10, y: 0, square: 'forestPine02' },
          { x: 11, y: 0, square: 'forestPine02' },
          { x: 12, y: 0, square: 'forestPine02' },

          { x: 0, y: 1, square: 'forestPine02' },
          { x: 1, y: 1, square: 'forestPine02' },
          { x: 2, y: 1, square: 'forestPine02' },
          { x: 3, y: 1, square: 'forestPine02' },
          { x: 4, y: 1, square: 'forestPine02' },
          { x: 5, y: 1, square: 'forestPine02' },
          { x: 6, y: 1, square: 'forestPine02' },
          { x: 7, y: 1, square: 'forestPine02' },
          { x: 8, y: 1, square: 'forestPine02' },
          { x: 9, y: 1, square: 'forestPine02' },
          { x: 10, y: 1, square: 'forestPine02' },
          { x: 11, y: 1, square: 'forestPine02' },
          { x: 12, y: 1, square: 'forestPine02' },

          { x: 0, y: 2, square: 'forestPine02' },
          { x: 1, y: 2, square: 'forestPine02' },
          { x: 2, y: 2, square: 'forestPine02' },
          { x: 3, y: 2, square: 'forestPine02' },
          { x: 4, y: 2, square: 'forestPine02' },
          { x: 5, y: 2, square: 'plains00' },
          { x: 6, y: 2, square: 'forestPine02' },
          { x: 7, y: 2, square: 'forestPine02' },
          { x: 8, y: 2, square: 'forestPine02' },
          { x: 9, y: 2, square: 'forestPine02' },
          { x: 10, y: 2, square: 'forestPine02' },
          { x: 11, y: 2, square: 'forestPine02' },
          { x: 12, y: 2, square: 'forestPine02' },

          { x: 0, y: 3, square: 'forestPine02' },
          { x: 1, y: 3, square: 'forestPine02' },
          { x: 2, y: 3, square: 'forestPine02' },
          { x: 3, y: 3, square: 'forestPine02' },
          { x: 4, y: 3, square: 'plains00' },
          { x: 5, y: 3, square: 'plains00' },
          { x: 6, y: 3, square: 'plains00' },
          { x: 7, y: 3, square: 'forestPine02' },
          { x: 8, y: 3, square: 'forestPine02' },
          { x: 9, y: 3, square: 'forestPine02' },
          { x: 10, y: 3, square: 'forestPine02' },
          { x: 11, y: 3, square: 'forestPine02' },
          { x: 12, y: 3, square: 'forestPine02' },

          { x: 0, y: 4, square: 'forestPine02' },
          { x: 1, y: 4, square: 'forestPine02' },
          { x: 2, y: 4, square: 'forestPine02' },
          { x: 3, y: 4, square: 'plains00' },
          { x: 4, y: 4, square: 'plains00' },
          { x: 5, y: 4, square: 'plains_castle00', bright: 2, dim: 3 },
          { x: 6, y: 4, square: 'plains00' },
          { x: 7, y: 4, square: 'plains00' },
          { x: 8, y: 4, square: 'forestPine02' },
          { x: 9, y: 4, square: 'forestPine02' },
          { x: 10, y: 4, square: 'forestPine02' },
          { x: 11, y: 4, square: 'forestPine02' },
          { x: 12, y: 4, square: 'forestPine02' },

          { x: 0, y: 5, square: 'forestPine02' },
          { x: 1, y: 5, square: 'mountain00' },
          { x: 2, y: 5, square: 'forestPine02' },
          { x: 3, y: 5, square: 'forestPine02' },
          { x: 4, y: 5, square: 'plains00' },
          { x: 5, y: 5, square: 'plains00' },
          { x: 6, y: 5, square: 'plains00' },
          { x: 7, y: 5, square: 'forestPine02' },
          { x: 8, y: 5, square: 'forestPine02' },
          { x: 9, y: 5, square: 'forestPine02' },
          { x: 10, y: 5, square: 'forestPine02' },
          { x: 11, y: 5, square: 'forestPine02' },
          { x: 12, y: 5, square: 'forestPine02' },

          { x: 0, y: 6, square: 'forestPine02' },
          { x: 1, y: 6, square: 'desertYellowBase01' },
          { x: 2, y: 6, square: 'mountain00' },
          { x: 3, y: 6, square: 'forestPine02' },
          { x: 4, y: 6, square: 'forestPine02' },
          { x: 5, y: 6, square: 'plains00' },
          { x: 6, y: 6, square: 'mountain00' },
          { x: 7, y: 6, square: 'mountain00' },
          { x: 8, y: 6, square: 'forestPine02' },
          { x: 9, y: 6, square: 'forestPine02' },
          { x: 10, y: 6, square: 'forestPine02' },
          { x: 11, y: 6, square: 'forestPine02' },
          { x: 12, y: 6, square: 'forestPine02' },

          { x: 0, y: 7, square: 'desertYellowBase01' },
          { x: 1, y: 7, square: 'desertYellowBase01' },
          { x: 2, y: 7, square: 'volcanoActive00', dim: 1 },
          { x: 3, y: 7, square: 'mountain00' },
          { x: 4, y: 7, square: 'forestPine02' },
          { x: 5, y: 7, square: 'mountain00' },
          { x: 6, y: 7, square: 'lake00' },
          { x: 7, y: 7, square: 'lake00' },
          { x: 8, y: 7, square: 'jungle00' },
          { x: 9, y: 7, square: 'forestPine02' },
          { x: 10, y: 7, square: 'forestPine02' },
          { x: 11, y: 7, square: 'forestPine02' },
          { x: 12, y: 7, square: 'forestPine02' },

          { x: 0, y: 8, square: 'forestPine02' },
          { x: 1, y: 8, square: 'desertYellowBase01' },
          { x: 2, y: 8, square: 'volcanoActive01', dim: 1 },
          { x: 3, y: 8, square: 'mountain00' },
          { x: 4, y: 8, square: 'forestPine02' },
          { x: 5, y: 8, square: 'mountain00' },
          { x: 6, y: 8, square: 'lake00' },
          { x: 7, y: 8, square: 'lake00' },
          { x: 8, y: 8, square: 'jungle00' },
          { x: 9, y: 8, square: 'forestPine02' },
          { x: 10, y: 8, square: 'forestPine02' },
          { x: 11, y: 8, square: 'forestPine02' },
          { x: 12, y: 8, square: 'forestPine02' },

          { x: 0, y: 9, square: 'forestPine02' },
          { x: 1, y: 9, square: 'forestPine02' },
          { x: 2, y: 9, square: 'forestPine02' },
          { x: 3, y: 9, square: 'forestPine02' },
          { x: 4, y: 9, square: 'forestPine02' },
          { x: 5, y: 9, square: 'forestPine02' },
          { x: 6, y: 9, square: 'forestPine02' },
          { x: 7, y: 9, square: 'forestPine02' },
          { x: 8, y: 9, square: 'forestPine02' },
          { x: 9, y: 9, square: 'forestPine02' },
          { x: 10, y: 9, square: 'forestPine02' },
          { x: 11, y: 9, square: 'forestPine02' },
          { x: 12, y: 9, square: 'forestPine02' },

          { x: 0, y: 10, square: 'forestPine02' },
          { x: 1, y: 10, square: 'forestPine02' },
          { x: 2, y: 10, square: 'forestPine02' },
          { x: 3, y: 10, square: 'forestPine02' },
          { x: 4, y: 10, square: 'forestPine02' },
          { x: 5, y: 10, square: 'forestPine02' },
          { x: 6, y: 10, square: 'forestPine02' },
          { x: 7, y: 10, square: 'forestPine02' },
          { x: 8, y: 10, square: 'forestPine02' },
          { x: 9, y: 10, square: 'forestPine02' },
          { x: 10, y: 10, square: 'plains00', addon: { graphic: 'stiltHouse04.png', zoom: 2  }, bright: 2, dim: 3 },
          { x: 11, y: 10, square: 'forestPine02' },
          { x: 12, y: 10, square: 'forestPine02' },

          { x: 0, y: 11, square: 'forestPine02' },
          { x: 1, y: 11, square: 'forestPine02' },
          { x: 2, y: 11, square: 'forestPine02' },
          { x: 3, y: 11, square: 'forestPine02' },
          { x: 4, y: 11, square: 'forestPine02' },
          { x: 5, y: 11, square: 'forestPine02' },
          { x: 6, y: 11, square: 'forestPine02' },
          { x: 7, y: 11, square: 'forestPine02' },
          { x: 8, y: 11, square: 'forestPine02' },
          { x: 9, y: 11, square: 'forestPine02' },
          { x: 10, y: 11, square: 'forestPine02' },
          { x: 11, y: 11, square: 'forestPine02' },
          { x: 12, y: 11, square: 'forestPine02' },
      ],
      squares: [
        'ashPlains00.png',
        'ashPlains01.png',
        'ashPlains02.png',
        'ashPlains03.png',
        'base00.png',
        'base01.png',
        'base02.png',
        'base03.png',
        'below_dirt00.png',
        'below_lava00.png',
        'below_lavaSea00.png',
        'below_void00.png',
        'below_void01.png',
        'below_void02.png',
        'below_void03.png',
        'below_water00.png',
        'below_waterCoastBoth00.png',
        'below_waterCoastEast00.png',
        'below_waterCoastWest00.png',
        'bog00.png',
        'bog01.png',
        'bog02.png',
        'bog03.png',
        'desertDunes00.png',
        'desertDunes01.png',
        'desertDunes02.png',
        'desertDunes03.png',
        'desertRedBase00.png',
        'desertRedBase01.png',
        'desertRedBase02.png',
        'desertRedBase03.png',
        'desertRedDirt00.png',
        'desertRedDirt01.png',
        'desertRedDirt02.png',
        'desertRedDirt03.png',
        'desertRedForest00.png',
        'desertRedForest01.png',
        'desertRedForest02.png',
        'desertRedForest03.png',
        'desertRedForestOasis00.png',
        'desertRedForestOasis01.png',
        'desertRedGrass00.png',
        'desertRedGrass01.png',
        'desertRedGrass02.png',
        'desertRedGrass03.png',
        'desertRedGrassDunes00.png',
        'desertRedGrassDunes01.png',
        'desertRedGrassDunes02.png',
        'desertRedGrassDunes03.png',
        'desertRedGrassOasis00.png',
        'desertRedGrassOasis01.png',
        'desertRedHills00.png',
        'desertRedHills01.png',
        'desertRedHills02.png',
        'desertRedHills03.png',
        'desertRedHillsOasis00.png',
        'desertRedHillsOasis01.png',
        'desertRedMountainLarge00.png',
        'desertRedMountainLargeCave00.png',
        'desertRedMountains00.png',
        'desertRedMountains01.png',
        'desertRedMountains02.png',
        'desertRedMountains03.png',
        'desertRedMountainsCave00.png',
        'desertRedMountainsCave01.png',
        'desertRedMountainsCave02.png',
        'desertRedMountainsCave03.png',
        'desertYellowBase00.png',
        'desertYellowBase01.png',
        'desertYellowBase02.png',
        'desertYellowBase03.png',
        'desertYellowCactiForest00.png',
        'desertYellowCactiForest01.png',
        'desertYellowCactiForest02.png',
        'desertYellowCactiForest03.png',
        'desertYellowCrater00.png',
        'desertYellowDirt00.png',
        'desertYellowDirt01.png',
        'desertYellowDirt02.png',
        'desertYellowDirt03.png',
        'desertYellowDirtDunes00.png',
        'desertYellowDirtDunes01.png',
        'desertYellowDirtDunes02.png',
        'desertYellowDirtDunes03.png',
        'desertYellowHills00.png',
        'desertYellowHills01.png',
        'desertYellowHills02.png',
        'desertYellowHills03.png',
        'desertYellowHillsOasis00.png',
        'desertYellowHillsOasis01.png',
        'desertYellowHillsOasis02.png',
        'desertYellowHillsOasis03.png',
        'desertYellowMesaLarge00.png',
        'desertYellowMesaLarge01.png',
        'desertYellowMesaLargeCave00.png',
        'desertYellowMesaLargeCave01.png',
        'desertYellowMesaLargeOasis00.png',
        'desertYellowMesaLargeOasis01.png',
        'desertYellowMesas00.png',
        'desertYellowMesas01.png',
        'desertYellowMesas02.png',
        'desertYellowMesas03.png',
        'desertYellowMesasCave00.png',
        'desertYellowMesasCave01.png',
        'desertYellowMesasCave02.png',
        'desertYellowMesasCave03.png',
        'desertYellowSaltFlat00.png',
        'desert_oasis00.png',
        'desert_oasis01.png',
        'desert_pyramid_ruins00.png',
        'desert_ruins00.png',
        'dirt00.png',
        'dirt01.png',
        'dirt02.png',
        'dirt03.png',
        'dirtCold00.png',
        'dirtCold01.png',
        'dirtCold02.png',
        'dirtCold03.png',
        'dirt_castle00.png',
        'dirt_castle01.png',
        'dirt_castle02.png',
        'dirt_castle_ruins00.png',
        'dirt_henge00.png',
        'dirt_inn00.png',
        'dirt_smithy00.png',
        'dirt_temple00.png',
        'dirt_temple_ruins00.png',
        'dirt_village00.png',
        'dirt_village01.png',
        'dirt_village02.png',
        'dirt_village03.png',
        'dirt_village_small00.png',
        'dirt_village_small01.png',
        'dirt_village_small02.png',
        'dirt_village_small03.png',
        'dirt_walled_city00.png',
        'forestBroadleaf00.png',
        'forestBroadleaf01.png',
        'forestBroadleaf02.png',
        'forestBroadleaf03.png',
        'forestBurnedAsh00.png',
        'forestBurnedAsh01.png',
        'forestBurnedAsh02.png',
        'forestBurnedAsh03.png',
        'forestBurnedAshNecroCastle.png',
        'forestBurnedDirt00.png',
        'forestBurnedDirt01.png',
        'forestBurnedDirt02.png',
        'forestBurnedDirt03.png',
        'forestPine00.png',
        'forestPine01.png',
        'forestPine02.png',
        'forestPine03.png',
        'forestPineClearing00.png',
        'forestPineLoggingCamp00.png',
        'forestPineSnowCovered00.png',
        'forestPineSnowCovered01.png',
        'forestPineSnowCovered02.png',
        'forestPineSnowCovered03.png',
        'forestPineSnowCoveredClearing00.png',
        'forestPineSnowCoveredLoggingCamp00.png',
        'forestPineSnowTransition00.png',
        'forestPineSnowTransition01.png',
        'forestPineSnowTransition02.png',
        'forestPineSnowTransition03.png',
        'forestPineSnowTransitionClearing00.png',
        'forestPineSnowTransitionLoggingCamp00.png',
        'forest_castle_ruins00.png',
        'forest_elven_lodge00.png',
        'forest_forester00.png',
        'forest_forester01.png',
        'fumarolePlains00.png',
        'fumarolePlains01.png',
        'fumarolePlains02.png',
        'fumarolePlains03.png',
        'grassySand00.png',
        'grassySand01.png',
        'grassySand02.png',
        'grassySand03.png',
        'grassySandPalms00.png',
        'grassySandPalms01.png',
        'grassySandPalms02.png',
        'grassySandPalms03.png',
        'highlands00.png',
        'highlands01.png',
        'highlands02.png',
        'highlands03.png',
        'hills00.png',
        'hills01.png',
        'hills02.png',
        'hills03.png',
        'hillsCold00.png',
        'hillsCold01.png',
        'hillsCold02.png',
        'hillsCold03.png',
        'hillsColdCave00.png',
        'hillsColdSnowCovered00.png',
        'hillsColdSnowCovered01.png',
        'hillsColdSnowCovered02.png',
        'hillsColdSnowCovered03.png',
        'hillsColdSnowCoveredCave00.png',
        'hillsColdSnowTransition00.png',
        'hillsColdSnowTransition01.png',
        'hillsColdSnowTransition02.png',
        'hillsColdSnowTransition03.png',
        'hillsColdSnowTransitionCave00.png',
        'hills_mine00.png',
        'hills_mine01.png',
        'hills_mine02.png',
        'hills_mine03.png',
        'islandRocky00.png',
        'islandRocky01.png',
        'islandRockyHouse00.png',
        'islandRockyTower00.png',
        'islandSandy00.png',
        'islandSandy01.png',
        'islandSandyShipWreck00.png',
        'islandSandyTemple00.png',
        'jungle00.png',
        'jungle01.png',
        'jungle02.png',
        'jungle03.png',
        'lake00.png',
        'lake01.png',
        'lake02.png',
        'lake03.png',
        'lavaField00.png',
        'lavaField01.png',
        'lavaField02.png',
        'lavaField03.png',
        'lavaFieldActive00.png',
        'lavaFieldActive01.png',
        'lavaFieldActive02.png',
        'lavaFieldActive03.png',
        'lavaSea00.png',
        'lavaSea01.png',
        'lavaSea02.png',
        'lavaSea03.png',
        'marsh00.png',
        'marsh01.png',
        'marsh02.png',
        'marsh03.png',
        'marsh_castle_ruins00.png',
        'marsh_graveyard_ruins00.png',
        'mountain00.png',
        'mountain01.png',
        'mountain02.png',
        'mountain03.png',
        'mountainRiverEast00.png',
        'mountainRiverSouth00.png',
        'mountainRiverWest00.png',
        'mountainSnow00.png',
        'mountainSnow01.png',
        'mountainSnow02.png',
        'mountainSnow03.png',
        'mountainSnowCave00.png',
        'mountainSnowCave01.png',
        'mountainSnowCave02.png',
        'mountainSnowCave03.png',
        'mountain_castle00.png',
        'mountain_cave00.png',
        'mountain_cave01.png',
        'mountain_dwarf_fortress00.png',
        'mountain_fortress00.png',
        'mountain_mine00.png',
        'mountain_mine01.png',
        'mountain_mine02.png',
        'mountain_mine03.png',
        'ocean00.png',
        'ocean01.png',
        'ocean02.png',
        'ocean03.png',
        'oceanCalm00.png',
        'oceanCalm01.png',
        'oceanCalm02.png',
        'oceanCalm03.png',
        'oceanCalmSeemless00.png',
        'oceanCalmSeemless01.png',
        'oceanCalmSeemless02.png',
        'oceanCalmSeemless03.png',
        'oceanHarborWhaling00.png',
        'oceanIcebergs00.png',
        'oceanIcebergs01.png',
        'oceanIcebergs02.png',
        'oceanIcebergs03.png',
        'oceanShellVillage00.png',
        'oceanShipWreck00.png',
        'oceanWhirlpool00.png',
        'plains00.png',
        'plains01.png',
        'plains02.png',
        'plains03.png',
        'plainsCold00.png',
        'plainsCold01.png',
        'plainsCold02.png',
        'plainsCold03.png',
        'plainsColdPond00.png',
        'plainsColdRuin00.png',
        'plainsColdRuinSnow00.png',
        'plainsColdSnowCovered00.png',
        'plainsColdSnowCovered01.png',
        'plainsColdSnowCovered02.png',
        'plainsColdSnowCovered03.png',
        'plainsColdSnowCoveredPond00.png',
        'plainsColdSnowTransition00.png',
        'plainsColdSnowTransition01.png',
        'plainsColdSnowTransition02.png',
        'plainsColdSnowTransition03.png',
        'plainsColdSnowTransitionPond00.png',
        'plains_castle00.png',
        'plains_castle01.png',
        'plains_castle02.png',
        'plains_elven_lodge00.png',
        'plains_farm00.png',
        'plains_farm01.png',
        'plains_farm02.png',
        'plains_farm03.png',
        'plains_henge00.png',
        'plains_inn00.png',
        'plains_smithy00.png',
        'plains_temple00.png',
        'plains_temple_ruins00.png',
        'plains_village00.png',
        'plains_village01.png',
        'plains_village02.png',
        'plains_village03.png',
        'plains_village_small00.png',
        'plains_village_small01.png',
        'plains_village_small02.png',
        'plains_village_small03.png',
        'plains_walled_city00.png',
        'sand00.png',
        'sand01.png',
        'sand02.png',
        'sand03.png',
        'sandPalms00.png',
        'sandPalms01.png',
        'sandPalms02.png',
        'sandPalms03.png',
        'scrubland00.png',
        'scrubland01.png',
        'scrubland02.png',
        'scrubland03.png',
        'snowField00.png',
        'snowField01.png',
        'snowField02.png',
        'snowField03.png',
        'snowFieldGiantSkeleton00.png',
        'snowFieldIcePalace00.png',
        'swamp00.png',
        'swamp01.png',
        'swamp02.png',
        'swamp03.png',
        'tropicalPlains00.png',
        'tropicalPlains01.png',
        'tropicalPlains02.png',
        'tropicalPlains03.png',
        'tropicalPlainsRuinMachine00.png',
        'tropicalPlainsSnakeTemple00.png',
        'tropicalPlainsSteppedPyramid00.png',
        'tropicalPlainsSteppedPyramidRuin00.png',
        'tropicalWaterfallHill00.png',
        'villageHalfling00.png',
        'void00.png',
        'void01.png',
        'void02.png',
        'void03.png',
        'volcanoActive00.png',
        'volcanoActive01.png',
        'volcanoActive02.png',
        'volcanoActive03.png',
        'volcanoCave00.png',
        'volcanoDormant00.png',
        'volcanoDormant01.png',
        'volcanoDormant02.png',
        'volcanoDormant03.png',
        'wetlands00.png',
        'wetlands01.png',
        'wetlands02.png',
        'wetlands03.png',
        'wetlandsSnakeTemple00.png',
        'wetlandsStiltVillage00.png',
        'woodlands00.png',
        'woodlands01.png',
        'woodlands02.png',
        'woodlands03.png',
      ],
      addons: [
        'bridgeEW00.png',
        'bridgeNS00.png',
        'burnedTree00.png',
        'burnedTree01.png',
        'burnedTree02.png',
        'burnedTree03.png',
        'burnedTree04.png',
        'burnedTree05.png',
        'burnedTree06.png',
        'burnedTree07.png',
        'cactus00.png',
        'cactus01.png',
        'cactus02.png',
        'cactus03.png',
        'cactus04.png',
        'cactus05.png',
        'cactus06.png',
        'cactus07.png',
        'cactus08.png',
        'castle.png',
        'castle2.png',
        'castle3.png',
        'castleRuinDirt.png',
        'castleRuinForest.png',
        'castleRuinMarsh.png',
        'coast0001-00.png',
        'coast0001-01.png',
        'coast0001-02.png',
        'coast0001-03.png',
        'coast0001-river0001-00.png',
        'coast0001-river0001-01.png',
        'coast0010-00.png',
        'coast0010-01.png',
        'coast0010-02.png',
        'coast0010-03.png',
        'coast0010-river0010-00.png',
        'coast0010-river0010-01.png',
        'coast0011-00.png',
        'coast0011-01.png',
        'coast0011-river0001-00.png',
        'coast0011-river0010-00.png',
        'coast0011-river0011-00.png',
        'coast0100-00.png',
        'coast0100-01.png',
        'coast0100-02.png',
        'coast0100-03.png',
        'coast0100-river0100-00.png',
        'coast0100-river0100-01.png',
        'coast0101-00.png',
        'coast0101-01.png',
        'coast0101-river0001-00.png',
        'coast0101-river0100-00.png',
        'coast0101-river0101-00.png',
        'coast0101-river0101-01.png',
        'coast0110-00.png',
        'coast0110-01.png',
        'coast0110-river0010-00.png',
        'coast0110-river0100-00.png',
        'coast0110-river0110-00.png',
        'coast0111-00.png',
        'coast0111-01.png',
        'coast0111-river0001-00.png',
        'coast0111-river0010-00.png',
        'coast0111-river0011-00.png',
        'coast0111-river0100-00.png',
        'coast0111-river0101-00.png',
        'coast0111-river0110-00.png',
        'coast0111-river0111-00.png',
        'coast1000-00.png',
        'coast1000-01.png',
        'coast1000-02.png',
        'coast1000-03.png',
        'coast1000-river1000-00.png',
        'coast1000-river1000-01.png',
        'coast1001-00.png',
        'coast1001-01.png',
        'coast1001-river0001-00.png',
        'coast1001-river1000-00.png',
        'coast1001-river1001-00.png',
        'coast1010-00.png',
        'coast1010-01.png',
        'coast1010-river0010-00.png',
        'coast1010-river1000-00.png',
        'coast1010-river1010-00.png',
        'coast1010-river1010-01.png',
        'coast1011-00.png',
        'coast1011-01.png',
        'coast1011-river0001-00.png',
        'coast1011-river0010-00.png',
        'coast1011-river0011-00.png',
        'coast1011-river1000-00.png',
        'coast1011-river1001-00.png',
        'coast1011-river1010-00.png',
        'coast1011-river1011-00.png',
        'coast1100-00.png',
        'coast1100-01.png',
        'coast1100-river0100-00.png',
        'coast1100-river1000-00.png',
        'coast1100-river1100-00.png',
        'coast1101-00.png',
        'coast1101-01.png',
        'coast1101-river0001-00.png',
        'coast1101-river0100-00.png',
        'coast1101-river1000-00.png',
        'coast1101-river1001-00.png',
        'coast1101-river1100-00.png',
        'coast1101-river1101-00.png',
        'coast1110-00.png',
        'coast1110-01.png',
        'coast1110-river0010-00.png',
        'coast1110-river0100-00.png',
        'coast1110-river0110-00.png',
        'coast1110-river1000-00.png',
        'coast1110-river1010-00.png',
        'coast1110-river1100-01.png',
        'coast1110-river1110-00.png',
        'coast1111-00.png',
        'coast1111-01.png',
        'coast1111-river0001-00.png',
        'coast1111-river0010-00.png',
        'coast1111-river0100-00.png',
        'coast1111-river0101-00.png',
        'coast1111-river0111-00.png',
        'coast1111-river1000-00.png',
        'coast1111-river1001-00.png',
        'coast1111-river1010-00.png',
        'coast1111-river1011-00.png',
        'coast1111-river1101-00.png',
        'coast1111-river1110-00.png',
        'coast1111-river1111-00.png',
        'coastCorner0001-00.png',
        'coastCorner0001-01.png',
        'coastCorner0010-00.png',
        'coastCorner0010-01.png',
        'coastCorner0011-00.png',
        'coastCorner0100-00.png',
        'coastCorner0100-01.png',
        'coastCorner0110-00.png',
        'coastCorner0111-00.png',
        'coastCorner1000-00.png',
        'coastCorner1000-01.png',
        'coastCorner1001-00.png',
        'coastCorner1011-00.png',
        'coastCorner1100-00.png',
        'coastCorner1101-00.png',
        'coastCorner1110-00.png',
        'coastCorner1111-00.png',
        'coldLandCave00.png',
        'coldLandCaveSnow00.png',
        'coldRuin00.png',
        'coldRuinSnowCovered00.png',
        'corral00.png',
        'corral01.png',
        'corral02.png',
        'cowSkull00.png',
        'crater00.png',
        'crater01.png',
        'crater02.png',
        'crater03.png',
        'crater04.png',
        'decorMountain00.png',
        'decorMountain01.png',
        'decorMountain02.png',
        'decorMountain03.png',
        'decorMountain04.png',
        'decorMountain05.png',
        'decorPond00.png',
        'decorPond01.png',
        'decorPond02.png',
        'decorPond03.png',
        'decorTreeCluster00.png',
        'decorTreeCluster01.png',
        'decorTreeCluster02.png',
        'desertOasis00.png',
        'desertOasis01.png',
        'desertOasis02.png',
        'desertOasis03.png',
        'desertRuins00.png',
        'desertRuins01.png',
        'desertRuins02.png',
        'desertRuins03.png',
        'desertRuins04.png',
        'desertShrub00.png',
        'desertShrub01.png',
        'desertShrub02.png',
        'desertShrub03.png',
        'desertTree00.png',
        'desertTree01.png',
        'desertTree02.png',
        'desertTree03.png',
        'desertTree04.png',
        'dwarf_fortress00.png',
        'elvenLodge.png',
        'farm00.png',
        'farm01.png',
        'farm02.png',
        'farm03.png',
        'field00.png',
        'field01.png',
        'field02.png',
        'field03.png',
        'field04.png',
        'field05.png',
        'field06.png',
        'field07.png',
        'field08.png',
        'field09.png',
        'field10.png',
        'field11.png',
        'field12.png',
        'field13.png',
        'field14.png',
        'forester_hut00.png',
        'forester_hut01.png',
        'forester_hut02.png',
        'forester_shed00.png',
        'forester_stumps00.png',
        'forester_stumps01.png',
        'fumarole00.png',
        'fumarole01.png',
        'fumarole02.png',
        'fumarole03.png',
        'fumarole04.png',
        'fumarole05.png',
        'giantSkeletonFrozen00.png',
        'grass00.png',
        'grass01.png',
        'grass02.png',
        'grass03.png',
        'grass04.png',
        'grass05.png',
        'grass06.png',
        'grass07.png',
        'grass08.png',
        'graveyard00.png',
        'halflingHouse00.png',
        'halflingHouse01.png',
        'halflingHouse02.png',
        'halflingHouse03.png',
        'halflingHouse04.png',
        'halflingHouse05.png',
        'harborWhalingDecor00.png',
        'harbor_crane.png',
        'harbor_whale.png',
        'hellgate.png',
        'hellgate_on.png',
        'hellgate_portal.png',
        'house00.png',
        'house01.png',
        'house02.png',
        'house03.png',
        'house04.png',
        'house05.png',
        'house06.png',
        'house07.png',
        'house08.png',
        'house09.png',
        'house10.png',
        'house11.png',
        'house12.png',
        'house13.png',
        'house14.png',
        'house15.png',
        'iceBerg00.png',
        'iceBerg01.png',
        'iceBerg02.png',
        'iceBerg03.png',
        'iceBerg04.png',
        'iceCrevasse00.png',
        'iceCrevasse01.png',
        'icePalace00.png',
        'inn.png',
        'innMossy.png',
        'islandRocky00.png',
        'islandRocky01.png',
        'islandRocky02.png',
        'islandRocky03.png',
        'islandRocky04.png',
        'islandRocky05.png',
        'islandRocky06.png',
        'islandSandy00.png',
        'islandSandy01.png',
        'islandSandy02.png',
        'jungleMachineRuin00.png',
        'junglePalm00.png',
        'junglePalm01.png',
        'junglePalm02.png',
        'junglePalm03.png',
        'junglePalm04.png',
        'jungleTree00.png',
        'jungleTree01.png',
        'jungleTree02.png',
        'jungleTree03.png',
        'jungleTree04.png',
        'jungleTree05.png',
        'lakeCold00.png',
        'lakeColdFrozen00.png',
        'lakeSmall00.png',
        'lakeSmall01.png',
        'lakeSmall02.png',
        'lakeSmall03.png',
        'lavaCone00.png',
        'lavaCone01.png',
        'lavaCone02.png',
        'lavaCone03.png',
        'lavaCone04.png',
        'lavaConeDormant00.png',
        'lavaConeDormant01.png',
        'lavaConeDormant02.png',
        'lavaConeDormant03.png',
        'lavaConeDormant04.png',
        'lavaCraterBig00.png',
        'lavaOutcrop00.png',
        'lavaOutcrop01.png',
        'lavaOutcrop02.png',
        'lavaRocks00.png',
        'lavaRocks01.png',
        'lavaRocks02.png',
        'lavaRocks03.png',
        'lavaRocks04.png',
        'lavaRocks05.png',
        'loggingCamp00.png',
        'loggingCamp01.png',
        'loggingCampSnow00.png',
        'loggingCampSnow01.png',
        'mine00.png',
        'mine01.png',
        'mine02.png',
        'mine03.png',
        'mines00.png',
        'mines01.png',
        'mines02.png',
        'mines03.png',
        'mines04.png',
        'mines05.png',
        'mountainCastle00.png',
        'mountainFortress.png',
        'mountainSnow00.png',
        'mountainSnow01.png',
        'mountainSnow02.png',
        'mountainSnow03.png',
        'mountainSnow04.png',
        'necroCastle.png',
        'oasis00.png',
        'oasis01.png',
        'obelisk00.png',
        'outcrop00.png',
        'outcrop01.png',
        'outcrop02.png',
        'outcrop03.png',
        'outcrop04.png',
        'palm00.png',
        'palm01.png',
        'palm02.png',
        'palm03.png',
        'palm04.png',
        'palm05.png',
        'palm06.png',
        'pyramid00.png',
        'pyramidSmall00.png',
        'pyramidSmall01.png',
        'redDesertDirt00.png',
        'redDesertDirt01.png',
        'redDesertDirt02.png',
        'redDesertGrass00.png',
        'redDesertGrass01.png',
        'redDesertGrass02.png',
        'redDesertGrass03.png',
        'redDesertGrass04.png',
        'redDesertGrass05.png',
        'redDesertGrass06.png',
        'redRock00.png',
        'redRock01.png',
        'redRock02.png',
        'redRock03.png',
        'redRock04.png',
        'redRock05.png',
        'redRock06.png',
        'redRockBig00.png',
        'redRockBig01.png',
        'redRockBig02.png',
        'redRockBig03.png',
        'redRockBig04.png',
        'redRockSmall00.png',
        'redRockSmall01.png',
        'redRockSmall02.png',
        'redRockSmall03.png',
        'redRockSmall04.png',
        'river0000-00.png',
        'river0001-00.png',
        'river0010-00.png',
        'river0011-00.png',
        'river0011-01.png',
        'river0100-00.png',
        'river0101-00.png',
        'river0101-01.png',
        'river0101-02.png',
        'river0101-03.png',
        'river0110-00.png',
        'river0110-01.png',
        'river0111-00.png',
        'river0111-01.png',
        'river0111-02.png',
        'river1000-00.png',
        'river1001-00.png',
        'river1001-01.png',
        'river1001-02.png',
        'river1010-00.png',
        'river1010-01.png',
        'river1010-02.png',
        'river1010-03.png',
        'river1011-00.png',
        'river1011-01.png',
        'river1011-02.png',
        'river1100-00.png',
        'river1100-01.png',
        'river1101-00.png',
        'river1101-01.png',
        'river1101-02.png',
        'river1110-00.png',
        'river1110-01.png',
        'river1110-02.png',
        'river1111-00.png',
        'river1111-01.png',
        'river1111-02.png',
        'river1111-03.png',
        'road_corner0101-00.png',
        'road_corner0101-01.png',
        'road_corner0110-00.png',
        'road_corner0110-01.png',
        'road_corner1001-00.png',
        'road_corner1001-01.png',
        'road_corner1010-00.png',
        'road_corner1010-01.png',
        'road_crossroads1111-00.png',
        'road_crossroads1111-01.png',
        'road_crossroads1111-02.png',
        'road_crossroads1111-03.png',
        'road_end0001-00.png',
        'road_end0010-00.png',
        'road_end0100-00.png',
        'road_end1000-00.png',
        'road_end_short0001-00.png',
        'road_end_short0010-00.png',
        'road_end_short0100-00.png',
        'road_end_short1000-00.png',
        'road_sheet00.png',
        'road_straight0011-00.png',
        'road_straight0011-01.png',
        'road_straight1100-00.png',
        'road_straight1100-01.png',
        'road_tee0111-00.png',
        'road_tee0111-01.png',
        'road_tee1011-00.png',
        'road_tee1011-01.png',
        'road_tee1101-00.png',
        'road_tee1101-01.png',
        'road_tee1110-00.png',
        'road_tee1110-01.png',
        'rocks00.png',
        'rocks01.png',
        'rocks02.png',
        'rocks03.png',
        'rocks04.png',
        'ship00.png',
        'shipWreck00.png',
        'sign00.png',
        'sign01.png',
        'smithy.png',
        'snakeTemple00.png',
        'standingStones.png',
        'standingStonesMossy.png',
        'SteppedPyramid00.png',
        'SteppedPyramidRuin00.png',
        'stiltHouse00.png',
        'stiltHouse01.png',
        'stiltHouse02.png',
        'stiltHouse03.png',
        'stiltHouse04.png',
        'swampStump00.png',
        'swampStump01.png',
        'swampStump02.png',
        'swampStump03.png',
        'swampStump04.png',
        'swampTree00.png',
        'swampTree01.png',
        'swampTree02.png',
        'swampTree03.png',
        'swampTree04.png',
        'swampTree05.png',
        'temple.png',
        'templeRuins.png',
        'treeA00.png',
        'treeA01.png',
        'treeA02.png',
        'treeA03.png',
        'treeA04.png',
        'treeB00.png',
        'treeB01.png',
        'treeB02.png',
        'treeB03.png',
        'treeB04.png',
        'treeC00.png',
        'treeC01.png',
        'treeC02.png',
        'treeC03.png',
        'treeC04.png',
        'treePine00.png',
        'treePine01.png',
        'treePine02.png',
        'treePine03.png',
        'treePine04.png',
        'treePine05.png',
        'treePineSnow00.png',
        'treePineSnow01.png',
        'treePineSnow02.png',
        'treePineSnow03.png',
        'treePineSnow04.png',
        'treePineSnow05.png',
        'treesA_cluster00.png',
        'treesA_cluster01.png',
        'treesA_line00.png',
        'treesA_line01.png',
        'treesA_line02.png',
        'treesA_line03.png',
        'treesA_line04.png',
        'treesA_line05.png',
        'tropicalHillWaterfall00.png',
        'village00.png',
        'village01.png',
        'village02.png',
        'village03.png',
        'villageHalflingDecor00.png',
        'villageSmall00.png',
        'villageSmall01.png',
        'villageSmall02.png',
        'villageSmall03.png',
        'volcanoCave.png',
        'walledCity.png',
        'walledCityMossy.png',
        'well00.png',
        'well01.png',
        'whirlpool00.png',
        'wizardTower00.png',
        'wizardTowerRuins00.png',
        'wizardTowerRuinsSnow00.png',
        'wizardTowerSnow00.png',
        'yellowDesertCrater00.png',
        'yellowRock00.png',
        'yellowRock01.png',
        'yellowRock02.png',
        'yellowRock03.png',
        'yellowRock04.png',
        'yellowRock05.png',
        'yellowRockBig00.png',
        'yellowRockBig01.png',
        'yellowRockBig02.png',
        'yellowRockBig03.png',
        'yellowRockBig04.png',
        'yellowRockSmall00.png',
        'yellowRockSmall01.png',
        'yellowRockSmall02.png',
        'yellowRockSmall03.png',
        'yellowRockSmall04.png'
      ]
    };
  },
  mounted: () => {
  }
};
</script>
